name: statRethinkPymc3
channels:
- defaults
dependencies:
  - python==3.7.2
  - statsmodels==0.10.0
  - nb_conda
  - numpy==1.16.0
  - pandas==0.23.4
  - seaborn==0.9.0
  - scipy==1.2.0
  - matplotlib==3.0.2
  - pip:
     - pymc3==3.6
     - arviz==0.4.1
